<?php

namespace Database\Seeders;

use App\Models\Personnel;
use App\Models\Department;
use Illuminate\Database\Seeder;

class PersonnelSeeder extends Seeder
{
    public function run(): void
    {
        $departments = Department::all();

        $personnel = [
            // ─── Monks ───
            [
                'gender' => 'monk',
                'title_lo' => 'ພຣະ',
                'title_en' => 'Phra',
                'first_name_lo' => 'ວິຈິດ',
                'first_name_en' => 'Vichit',
                'last_name_lo' => 'ທັມມະຣົງ',
                'last_name_en' => 'Dhammarong',
                'name_lo' => 'ພຣະ ວິຈິດ ທັມມະຣົງ',
                'name_en' => 'Phra Vichit Dhammarong',
                'position_lo' => 'ອາຈານສອນພຣະປະຣິຍັດຕິທັມ',
                'position_en' => 'Religious Instructor',
                'department_id' => $departments->where('name_en', 'Education Department')->first()?->id,
                'current_temple_lo' => 'ວັດສີສະເກດ',
                'current_temple_en' => 'Wat Si Saket',
                'date_of_ordination' => '2010-07-15',
                'pansa' => 15,
                'email' => 'vichit@temple.org',
                'phone' => '+856 20 5555 0001',
                'education_lo' => 'ປະລິນຍາໂທ ພຸດທະສາດ',
                'education_en' => 'Master of Buddhist Studies',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1985-03-12',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'gender' => 'monk',
                'title_lo' => 'ພຣະອາຈານ',
                'title_en' => 'Most Ven.',
                'first_name_lo' => 'ສຸວັນ',
                'first_name_en' => 'Souvanh',
                'last_name_lo' => 'ພົມມະວົງ',
                'last_name_en' => 'Phommavong',
                'name_lo' => 'ພຣະອາຈານ ສຸວັນ ພົມມະວົງ',
                'name_en' => 'Most Ven. Souvanh Phommavong',
                'position_lo' => 'ຫົວໜ້າພະແນກທັມມະ',
                'position_en' => 'Head of Dhamma Department',
                'department_id' => $departments->where('name_en', 'Dhamma Department')->first()?->id,
                'current_temple_lo' => 'ວັດທາດຫຼວງ',
                'current_temple_en' => 'Wat That Luang',
                'date_of_ordination' => '2000-05-20',
                'pansa' => 25,
                'education_lo' => 'ປະລິນຍາເອກ ພຸດທະສາດ',
                'education_en' => 'PhD in Buddhist Studies',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1975-08-01',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'gender' => 'monk',
                'title_lo' => 'ສາມະເນນ',
                'title_en' => 'Novice',
                'first_name_lo' => 'ເຄນ',
                'first_name_en' => 'Khene',
                'last_name_lo' => 'ວໍຣະສັກ',
                'last_name_en' => 'Vorasack',
                'name_lo' => 'ສາມະເນນ ເຄນ ວໍຣະສັກ',
                'name_en' => 'Novice Khene Vorasack',
                'position_lo' => 'ນັກຮຽນສົງ',
                'position_en' => 'Student Monk',
                'department_id' => $departments->where('name_en', 'Education Department')->first()?->id,
                'current_temple_lo' => 'ວັດອົງຕື້',
                'current_temple_en' => 'Wat Ong Teu',
                'date_of_ordination' => '2023-04-10',
                'pansa' => 2,
                'province_lo' => 'ສະຫວັນນະເຂດ',
                'province_en' => 'Savannakhet',
                'date_of_birth' => '2005-11-22',
                'sort_order' => 10,
                'is_active' => false,
            ],
            [
                'gender' => 'monk',
                'title_lo' => 'ພຣະຄູ',
                'title_en' => 'Phrakhu',
                'first_name_lo' => 'ບຸນມາ',
                'first_name_en' => 'Bounma',
                'last_name_lo' => 'ແສງຈັນ',
                'last_name_en' => 'Saengchanh',
                'name_lo' => 'ພຣະຄູ ບຸນມາ ແສງຈັນ',
                'name_en' => 'Phrakhu Bounma Saengchanh',
                'position_lo' => 'ຜູ້ຊ່ວຍຫົວໜ້າ ພະແນກການສຶກສາ',
                'position_en' => 'Assistant Head of Education',
                'department_id' => $departments->where('name_en', 'Education Department')->first()?->id,
                'current_temple_lo' => 'ວັດໂພນໄຊ',
                'current_temple_en' => 'Wat Phon Xai',
                'date_of_ordination' => '2005-06-18',
                'pansa' => 20,
                'province_lo' => 'ຫຼວງພະບາງ',
                'province_en' => 'Luang Prabang',
                'date_of_birth' => '1980-01-15',
                'sort_order' => 3,
                'is_active' => true,
            ],

            // ─── Male Laypersons ───
            [
                'gender' => 'male',
                'title_lo' => 'ທ່ານ',
                'title_en' => 'Mr.',
                'first_name_lo' => 'ສົມພອນ',
                'first_name_en' => 'Somphone',
                'last_name_lo' => 'ໄຊຍະວົງ',
                'last_name_en' => 'Xayavong',
                'name_lo' => 'ທ້າວ ສົມພອນ ໄຊຍະວົງ',
                'name_en' => 'Mr. Somphone Xayavong',
                'position_lo' => 'ຫົວໜ້າພະແນກໄອທີ',
                'position_en' => 'IT Department Head',
                'department_id' => $departments->where('name_en', 'Operations Department')->first()?->id,
                'email' => 'somphone@temple.org',
                'phone' => '+856 20 5555 0002',
                'education_lo' => 'ປະລິນຍາຕີ ວິທະຍາສາດຄອມພິວເຕີ',
                'education_en' => 'Bachelor of Computer Science',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1990-06-15',
                'term_start' => 2022,
                'term_end' => 2026,
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'gender' => 'male',
                'title_lo' => 'ທ່ານ ດຣ.',
                'title_en' => 'Dr.',
                'first_name_lo' => 'ພູວົງ',
                'first_name_en' => 'Phouvong',
                'last_name_lo' => 'ສີສຸລິດ',
                'last_name_en' => 'Sisoulit',
                'name_lo' => 'ທ່ານ ດຣ. ພູວົງ ສີສຸລິດ',
                'name_en' => 'Dr. Phouvong Sisoulit',
                'position_lo' => 'ທີ່ປຶກສາອາວຸໂສ',
                'position_en' => 'Senior Advisor',
                'department_id' => $departments->where('name_en', 'Operations Department')->first()?->id,
                'email' => 'phouvong@temple.org',
                'phone' => '+856 20 5555 0003',
                'education_lo' => 'ປະລິນຍາເອກ ບໍລິຫານ',
                'education_en' => 'PhD in Administration',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1970-09-20',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'gender' => 'male',
                'title_lo' => 'ທ່ານ',
                'title_en' => 'Mr.',
                'first_name_lo' => 'ກິດຕິພົງ',
                'first_name_en' => 'Kittiphong',
                'last_name_lo' => 'ວົງພະຈັນ',
                'last_name_en' => 'Vongphachanh',
                'name_lo' => 'ທ່ານ ກິດຕິພົງ ວົງພະຈັນ',
                'name_en' => 'Mr. Kittiphong Vongphachanh',
                'position_lo' => 'ຜູ້ປະສານງານ',
                'position_en' => 'Coordinator',
                'department_id' => $departments->where('name_en', 'Public Relations Department')->first()?->id,
                'phone' => '+856 20 5555 0008',
                'province_lo' => 'ຈຳປາສັກ',
                'province_en' => 'Champasak',
                'date_of_birth' => '1995-04-18',
                'sort_order' => 8,
                'is_active' => true,
            ],

            // ─── Female Laypersons ───
            [
                'gender' => 'female',
                'title_lo' => 'ນາງ',
                'title_en' => 'Mrs.',
                'first_name_lo' => 'ຈັນທາ',
                'first_name_en' => 'Chantha',
                'last_name_lo' => 'ພິລາວົງ',
                'last_name_en' => 'Philavong',
                'name_lo' => 'ນາງ ຈັນທາ ພິລາວົງ',
                'name_en' => 'Mrs. Chantha Philavong',
                'position_lo' => 'ນາຍບັນຊີ',
                'position_en' => 'Senior Accountant',
                'department_id' => $departments->where('name_en', 'Finance Department')->first()?->id,
                'email' => 'chantha@temple.org',
                'phone' => '+856 20 5555 0004',
                'education_lo' => 'ປະລິນຍາຕີ ບັນຊີ',
                'education_en' => 'Bachelor of Accounting',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1988-12-05',
                'term_start' => 2020,
                'term_end' => 2024,
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'gender' => 'female',
                'title_lo' => 'ນາງສາວ',
                'title_en' => 'Ms.',
                'first_name_lo' => 'ມະນີວອນ',
                'first_name_en' => 'Manivone',
                'last_name_lo' => 'ດວງຈັນ',
                'last_name_en' => 'Douangchanh',
                'name_lo' => 'ນາງສາວ ມະນີວອນ ດວງຈັນ',
                'name_en' => 'Ms. Manivone Douangchanh',
                'position_lo' => 'ເລຂາ',
                'position_en' => 'Secretary',
                'department_id' => $departments->where('name_en', 'Operations Department')->first()?->id,
                'email' => 'manivone@temple.org',
                'phone' => '+856 20 5555 0005',
                'education_lo' => 'ປະລິນຍາຕີ ບໍລິຫານ',
                'education_en' => 'Bachelor of Administration',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1992-07-30',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'gender' => 'female',
                'title_lo' => 'ນາງ',
                'title_en' => 'Mrs.',
                'first_name_lo' => 'ສຸພາ',
                'first_name_en' => 'Soupha',
                'last_name_lo' => 'ແກ້ວບຸນເຮືອງ',
                'last_name_en' => 'Kaeobounheuang',
                'name_lo' => 'ນາງ ສຸພາ ແກ້ວບຸນເຮືອງ',
                'name_en' => 'Mrs. Soupha Kaeobounheuang',
                'position_lo' => 'ຫົວໜ້າພະແນກສະຫວັດດີການ',
                'position_en' => 'Head of Welfare Department',
                'department_id' => $departments->where('name_en', 'Welfare Department')->first()?->id,
                'email' => 'soupha@temple.org',
                'phone' => '+856 20 5555 0006',
                'education_lo' => 'ປະລິນຍາໂທ ສັງຄົມສົງເຄາະ',
                'education_en' => 'Master of Social Work',
                'province_lo' => 'ນະຄອນຫຼວງວຽງຈັນ',
                'province_en' => 'Vientiane Capital',
                'date_of_birth' => '1982-02-14',
                'sort_order' => 9,
                'is_active' => true,
            ],
        ];

        foreach ($personnel as $person) {
            Personnel::create($person);
        }
    }
}
